export const OPENAPI_SCHEMAS_DIR = 'schemas/openapi'
export const OTHER_SCHEMAS_DIR = 'schemas/other'
export const OPENAPI_TYPES_DIR = 'src/generated/v2/openapi'
export const SCOPES_OUTPUT_FILE = 'src/generated/v2/other/scopes.ts'
export const OTHER_TYPES_DIR = 'src/generated/v2/other'
