// Generated by Bun plugin at 11/21/2024, 1:27:44 PM
declare namespace NodeJS {
    export interface ProcessEnv {
		CLIENT_ID: string
		CLIENT_SECRET: string
		PRIVATE_TOKEN: string
		API_BASE_URL: string
		REDIRECT_URL: string
		APP_ID: string
		DOCS_USERNAME: string
		DOCS_PASSWORD: string
		NPM_TOKEN: string
		HIGHLEVEL_API_KEY: string
		DOCS_API_URL: string
		GITHUB_TOKEN: string
		SSO_KEY: string
		JWT_SECRET: string
    }
}


//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

declare module '*.css' {
	const content: string
	export default content
}
