// Generated by Bun plugin at 10/11/2024, 1:38:14 PM
declare namespace NodeJS {
	export interface ProcessEnv {
		CLIENT_ID: string
		CLIENT_SECRET: string
		API_BASE_URL: string
		REDIRECT_URL: string
		SSO_KEY: string
		APP_ID: string
		JWT_SECRET: string
		DOCS_USERNAME: string
		DOCS_PASSWORD: string
	}
}

//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

declare module '*.css' {
	const content: string
	export default content
}
