// This file is generated by the generate-base-client.ts script.
// Do not edit directly.

import type { Client } from 'openapi-fetch'
import createClient from 'openapi-fetch'
import type { HighLevelClientInterface } from '..'
import type { DefaultOauthClient, OauthClientImpl } from '../oauth/impl'
import type { AccessType } from '../scopes/scope-types'
import type { paths as AgenciesPaths } from '../types/agencies'
import type { paths as AssociationsPaths } from '../types/associations'
import type { paths as BlogsPaths } from '../types/blogs'
import type { paths as BusinessesPaths } from '../types/businesses'
import type { paths as CalendarsPaths } from '../types/calendars'
import type { paths as CampaignsPaths } from '../types/campaigns'
import type { paths as CompaniesPaths } from '../types/companies'
import type { paths as ContactsPaths } from '../types/contacts'
import type { paths as ConversationsPaths } from '../types/conversations'
import type { paths as CoursesPaths } from '../types/courses'
import type { paths as CustomFieldsPaths } from '../types/custom-fields'
import type { paths as CustomMenusPaths } from '../types/custom-menus'
import type { paths as EmailIsvPaths } from '../types/email-isv'
import type { paths as EmailsPaths } from '../types/emails'
import type { paths as FormsPaths } from '../types/forms'
import type { paths as FunnelsPaths } from '../types/funnels'
import type { paths as InvoicesPaths } from '../types/invoices'
import type { paths as LinksPaths } from '../types/links'
import type { paths as LocationsPaths } from '../types/locations'
import type { paths as MarketplacePaths } from '../types/marketplace'
import type { paths as MediasPaths } from '../types/medias'
// type imports
import type { paths as OauthPaths } from '../types/oauth'
import type { paths as ObjectsPaths } from '../types/objects'
import type { paths as OpportunitiesPaths } from '../types/opportunities'
import type { paths as PaymentsPaths } from '../types/payments'
import type { paths as PhoneSystemPaths } from '../types/phone-system'
import type { paths as ProductsPaths } from '../types/products'
import type { paths as ProposalsPaths } from '../types/proposals'
import type { paths as SaasApiPaths } from '../types/saas-api'
import type { paths as SnapshotsPaths } from '../types/snapshots'
import type { paths as SocialMediaPostingPaths } from '../types/social-media-posting'
import type { paths as StorePaths } from '../types/store'
import type { paths as SurveysPaths } from '../types/surveys'
import type { paths as UsersPaths } from '../types/users'
import type { paths as VoiceAiPaths } from '../types/voice-ai'
import type { paths as WorkflowsPaths } from '../types/workflows'
import { createClientMaybeAuth } from './client-type-helpers'
import type { HighLevelClientConfig } from './default'
import { DEFAULT_V2_BASE_URL } from './default'
import type { AUTH_HEADERS } from './types'

/**
 * Base implementation for HighLevel API client.
 * Provides endpoint clients for each API domain.
 */
export class BaseHighLevelClient<
	T extends AccessType,
	TOAuth extends DefaultOauthClient | OauthClientImpl<T>,
> implements HighLevelClientInterface<T, TOAuth>
{
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth

	agencies: Client<AgenciesPaths>
	associations: Client<AssociationsPaths>
	blogs: Client<BlogsPaths>
	businesses: Client<BusinessesPaths>
	calendars: Client<CalendarsPaths>
	campaigns: Client<CampaignsPaths>
	companies: Client<CompaniesPaths>
	contacts: Client<ContactsPaths>
	conversations: Client<ConversationsPaths>
	courses: Client<CoursesPaths>
	customFields: Client<CustomFieldsPaths>
	customMenus: Client<CustomMenusPaths>
	emailIsv: Client<EmailIsvPaths>
	emails: Client<EmailsPaths>
	forms: Client<FormsPaths>
	funnels: Client<FunnelsPaths>
	invoices: Client<InvoicesPaths>
	links: Client<LinksPaths>
	locations: Client<LocationsPaths>
	marketplace: Client<MarketplacePaths>
	medias: Client<MediasPaths>
	objects: Client<ObjectsPaths>
	opportunities: Client<OpportunitiesPaths>
	payments: Client<PaymentsPaths>
	phoneSystem: Client<PhoneSystemPaths>
	products: Client<ProductsPaths>
	proposals: Client<ProposalsPaths>
	saasApi: Client<SaasApiPaths>
	snapshots: Client<SnapshotsPaths>
	socialMediaPosting: Client<SocialMediaPostingPaths>
	store: Client<StorePaths>
	surveys: Client<SurveysPaths>
	users: Client<UsersPaths>
	voiceAi: Client<VoiceAiPaths>
	workflows: Client<WorkflowsPaths>

	constructor(
		clientConfig?: HighLevelClientConfig,
		authHeaders?: AUTH_HEADERS,
	) {
		this._clientConfig = {
			...clientConfig,
			baseUrl: clientConfig?.baseUrl ?? DEFAULT_V2_BASE_URL,
		}
		if (authHeaders) {
			this._clientConfig.headers = {
				...this._clientConfig.headers,
				...authHeaders,
			}
		}

		// base oauth client
		this.oauth = createClient<OauthPaths>(this._clientConfig) as TOAuth

		// generate methods
		/**
		 * agencies client implementation.
		 */
		this.agencies = createClientMaybeAuth<
			AgenciesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<AgenciesPaths>
		/**
		 * associations client implementation.
		 */
		this.associations = createClientMaybeAuth<
			AssociationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<AssociationsPaths>
		/**
		 * blogs client implementation.
		 */
		this.blogs = createClientMaybeAuth<BlogsPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<BlogsPaths>
		/**
		 * businesses client implementation.
		 */
		this.businesses = createClientMaybeAuth<
			BusinessesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<BusinessesPaths>
		/**
		 * calendars client implementation.
		 */
		this.calendars = createClientMaybeAuth<
			CalendarsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CalendarsPaths>
		/**
		 * campaigns client implementation.
		 */
		this.campaigns = createClientMaybeAuth<
			CampaignsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CampaignsPaths>
		/**
		 * companies client implementation.
		 */
		this.companies = createClientMaybeAuth<
			CompaniesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CompaniesPaths>
		/**
		 * contacts client implementation.
		 */
		this.contacts = createClientMaybeAuth<
			ContactsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<ContactsPaths>
		/**
		 * conversations client implementation.
		 */
		this.conversations = createClientMaybeAuth<
			ConversationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<ConversationsPaths>
		/**
		 * courses client implementation.
		 */
		this.courses = createClientMaybeAuth<
			CoursesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CoursesPaths>
		/**
		 * customFields client implementation.
		 */
		this.customFields = createClientMaybeAuth<
			CustomFieldsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CustomFieldsPaths>
		/**
		 * customMenus client implementation.
		 */
		this.customMenus = createClientMaybeAuth<
			CustomMenusPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<CustomMenusPaths>
		/**
		 * emailIsv client implementation.
		 */
		this.emailIsv = createClientMaybeAuth<
			EmailIsvPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<EmailIsvPaths>
		/**
		 * emails client implementation.
		 */
		this.emails = createClientMaybeAuth<EmailsPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<EmailsPaths>
		/**
		 * forms client implementation.
		 */
		this.forms = createClientMaybeAuth<FormsPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<FormsPaths>
		/**
		 * funnels client implementation.
		 */
		this.funnels = createClientMaybeAuth<
			FunnelsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<FunnelsPaths>
		/**
		 * invoices client implementation.
		 */
		this.invoices = createClientMaybeAuth<
			InvoicesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<InvoicesPaths>
		/**
		 * links client implementation.
		 */
		this.links = createClientMaybeAuth<LinksPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<LinksPaths>
		/**
		 * locations client implementation.
		 */
		this.locations = createClientMaybeAuth<
			LocationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<LocationsPaths>
		/**
		 * marketplace client implementation.
		 */
		this.marketplace = createClientMaybeAuth<
			MarketplacePaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<MarketplacePaths>
		/**
		 * medias client implementation.
		 */
		this.medias = createClientMaybeAuth<MediasPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<MediasPaths>
		/**
		 * objects client implementation.
		 */
		this.objects = createClientMaybeAuth<
			ObjectsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<ObjectsPaths>
		/**
		 * opportunities client implementation.
		 */
		this.opportunities = createClientMaybeAuth<
			OpportunitiesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<OpportunitiesPaths>
		/**
		 * payments client implementation.
		 */
		this.payments = createClientMaybeAuth<
			PaymentsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<PaymentsPaths>
		/**
		 * phoneSystem client implementation.
		 */
		this.phoneSystem = createClientMaybeAuth<
			PhoneSystemPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<PhoneSystemPaths>
		/**
		 * products client implementation.
		 */
		this.products = createClientMaybeAuth<
			ProductsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<ProductsPaths>
		/**
		 * proposals client implementation.
		 */
		this.proposals = createClientMaybeAuth<
			ProposalsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<ProposalsPaths>
		/**
		 * saasApi client implementation.
		 */
		this.saasApi = createClientMaybeAuth<
			SaasApiPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<SaasApiPaths>
		/**
		 * snapshots client implementation.
		 */
		this.snapshots = createClientMaybeAuth<
			SnapshotsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<SnapshotsPaths>
		/**
		 * socialMediaPosting client implementation.
		 */
		this.socialMediaPosting = createClientMaybeAuth<
			SocialMediaPostingPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<SocialMediaPostingPaths>
		/**
		 * store client implementation.
		 */
		this.store = createClientMaybeAuth<StorePaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<StorePaths>
		/**
		 * surveys client implementation.
		 */
		this.surveys = createClientMaybeAuth<
			SurveysPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<SurveysPaths>
		/**
		 * users client implementation.
		 */
		this.users = createClientMaybeAuth<UsersPaths, AUTH_HEADERS | undefined>(
			authHeaders,
			this._clientConfig,
		) as Client<UsersPaths>
		/**
		 * voiceAi client implementation.
		 */
		this.voiceAi = createClientMaybeAuth<
			VoiceAiPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<VoiceAiPaths>
		/**
		 * workflows client implementation.
		 */
		this.workflows = createClientMaybeAuth<
			WorkflowsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as Client<WorkflowsPaths>
	}
}
