// This file is generated by the generate-base-client.ts script.
// Do not edit directly.

import createClient from 'openapi-fetch'
import type { AccessType } from '../scopes/scope-types'
import type { HighLevelClientInterface } from '..'
import type { DefaultOauthClient, OauthClientImpl } from '../oauth/impl'
import type { paths as AdManagerPaths } from '../types/ad-manager'
import type { paths as AffiliateManagerPaths } from '../types/affiliate-manager'
import type { paths as AgenciesPaths } from '../types/agencies'
import type { paths as AgentStudioPaths } from '../types/agent-studio'
import type { paths as AssociationsPaths } from '../types/associations'
import type { paths as BlogsPaths } from '../types/blogs'
import type { paths as BrandBoardsPaths } from '../types/brand-boards'
import type { paths as BusinessesPaths } from '../types/businesses'
import type { paths as CalendarsPaths } from '../types/calendars'
import type { paths as CampaignsPaths } from '../types/campaigns'
import type { paths as CompaniesPaths } from '../types/companies'
import type { paths as ContactsPaths } from '../types/contacts'
import type { paths as ConversationAiPaths } from '../types/conversation-ai'
import type { paths as ConversationsPaths } from '../types/conversations'
import type { paths as CoursesPaths } from '../types/courses'
import type { paths as CustomFieldsPaths } from '../types/custom-fields'
import type { paths as CustomMenusPaths } from '../types/custom-menus'
import type { paths as EmailIsvPaths } from '../types/email-isv'
import type { paths as EmailsPaths } from '../types/emails'
import type { paths as FormsPaths } from '../types/forms'
import type { paths as FunnelsPaths } from '../types/funnels'
import type { paths as InvoicesPaths } from '../types/invoices'
import type { paths as KnowledgeBasePaths } from '../types/knowledge-base'
import type { paths as LinksPaths } from '../types/links'
import type { paths as LocationsPaths } from '../types/locations'
import type { paths as MarketplacePaths } from '../types/marketplace'
import type { paths as MediasPaths } from '../types/medias'
import type { paths as ObjectsPaths } from '../types/objects'
import type { paths as OpportunitiesPaths } from '../types/opportunities'
import type { paths as PaymentsPaths } from '../types/payments'
import type { paths as PhoneSystemPaths } from '../types/phone-system'
import type { paths as ProductsPaths } from '../types/products'
import type { paths as ProposalsPaths } from '../types/proposals'
import type { paths as SaasApiPaths } from '../types/saas-api'
import type { paths as SnapshotsPaths } from '../types/snapshots'
import type { paths as SocialMediaPostingPaths } from '../types/social-media-posting'
import type { paths as StorePaths } from '../types/store'
import type { paths as SurveysPaths } from '../types/surveys'
import type { paths as UsersPaths } from '../types/users'
import type { paths as VoiceAiPaths } from '../types/voice-ai'
import type { paths as WorkflowsPaths } from '../types/workflows'
import type { HighLevelClientConfig } from './default'
import { DEFAULT_V2_BASE_URL } from './default'
import { createClientMaybeAuth } from './client-type-helpers'
import type { AUTH_HEADERS, ClientForAuth } from './types'

import type { paths as OauthPaths } from '../types/oauth'

/**
 * Base implementation for HighLevel API client.
 * Provides endpoint clients for each API domain.
 */
export class BaseHighLevelClient<
	T extends AccessType,
	TOAuth extends DefaultOauthClient | OauthClientImpl<T>,
	TWithAuth extends boolean = false,
> implements HighLevelClientInterface<T, TOAuth> {
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth

	adManager: ClientForAuth<AdManagerPaths, TWithAuth>
	affiliateManager: ClientForAuth<AffiliateManagerPaths, TWithAuth>
	agencies: ClientForAuth<AgenciesPaths, TWithAuth>
	agentStudio: ClientForAuth<AgentStudioPaths, TWithAuth>
	associations: ClientForAuth<AssociationsPaths, TWithAuth>
	blogs: ClientForAuth<BlogsPaths, TWithAuth>
	brandBoards: ClientForAuth<BrandBoardsPaths, TWithAuth>
	businesses: ClientForAuth<BusinessesPaths, TWithAuth>
	calendars: ClientForAuth<CalendarsPaths, TWithAuth>
	campaigns: ClientForAuth<CampaignsPaths, TWithAuth>
	companies: ClientForAuth<CompaniesPaths, TWithAuth>
	contacts: ClientForAuth<ContactsPaths, TWithAuth>
	conversationAi: ClientForAuth<ConversationAiPaths, TWithAuth>
	conversations: ClientForAuth<ConversationsPaths, TWithAuth>
	courses: ClientForAuth<CoursesPaths, TWithAuth>
	customFields: ClientForAuth<CustomFieldsPaths, TWithAuth>
	customMenus: ClientForAuth<CustomMenusPaths, TWithAuth>
	emailIsv: ClientForAuth<EmailIsvPaths, TWithAuth>
	emails: ClientForAuth<EmailsPaths, TWithAuth>
	forms: ClientForAuth<FormsPaths, TWithAuth>
	funnels: ClientForAuth<FunnelsPaths, TWithAuth>
	invoices: ClientForAuth<InvoicesPaths, TWithAuth>
	knowledgeBase: ClientForAuth<KnowledgeBasePaths, TWithAuth>
	links: ClientForAuth<LinksPaths, TWithAuth>
	locations: ClientForAuth<LocationsPaths, TWithAuth>
	marketplace: ClientForAuth<MarketplacePaths, TWithAuth>
	medias: ClientForAuth<MediasPaths, TWithAuth>
	objects: ClientForAuth<ObjectsPaths, TWithAuth>
	opportunities: ClientForAuth<OpportunitiesPaths, TWithAuth>
	payments: ClientForAuth<PaymentsPaths, TWithAuth>
	phoneSystem: ClientForAuth<PhoneSystemPaths, TWithAuth>
	products: ClientForAuth<ProductsPaths, TWithAuth>
	proposals: ClientForAuth<ProposalsPaths, TWithAuth>
	saasApi: ClientForAuth<SaasApiPaths, TWithAuth>
	snapshots: ClientForAuth<SnapshotsPaths, TWithAuth>
	socialMediaPosting: ClientForAuth<SocialMediaPostingPaths, TWithAuth>
	store: ClientForAuth<StorePaths, TWithAuth>
	surveys: ClientForAuth<SurveysPaths, TWithAuth>
	users: ClientForAuth<UsersPaths, TWithAuth>
	voiceAi: ClientForAuth<VoiceAiPaths, TWithAuth>
	workflows: ClientForAuth<WorkflowsPaths, TWithAuth>

	constructor(
		clientConfig?: HighLevelClientConfig,
		authHeaders?: AUTH_HEADERS,
	) {
		this._clientConfig = {
			...clientConfig,
			baseUrl: clientConfig?.baseUrl ?? DEFAULT_V2_BASE_URL,
		}
		if (authHeaders) {
			this._clientConfig.headers = {
				...this._clientConfig.headers,
				...authHeaders,
			}
		}

		// base oauth client
		this.oauth = createClient<OauthPaths>(this._clientConfig) as TOAuth

		// generate methods
		/**
		 * adManager client implementation.
		 */
		this.adManager = createClientMaybeAuth<
			AdManagerPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			AdManagerPaths,
			TWithAuth
		>
		/**
		 * affiliateManager client implementation.
		 */
		this.affiliateManager = createClientMaybeAuth<
			AffiliateManagerPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			AffiliateManagerPaths,
			TWithAuth
		>
		/**
		 * agencies client implementation.
		 */
		this.agencies = createClientMaybeAuth<
			AgenciesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			AgenciesPaths,
			TWithAuth
		>
		/**
		 * agentStudio client implementation.
		 */
		this.agentStudio = createClientMaybeAuth<
			AgentStudioPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			AgentStudioPaths,
			TWithAuth
		>
		/**
		 * associations client implementation.
		 */
		this.associations = createClientMaybeAuth<
			AssociationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			AssociationsPaths,
			TWithAuth
		>
		/**
		 * blogs client implementation.
		 */
		this.blogs = createClientMaybeAuth<
			BlogsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			BlogsPaths,
			TWithAuth
		>
		/**
		 * brandBoards client implementation.
		 */
		this.brandBoards = createClientMaybeAuth<
			BrandBoardsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			BrandBoardsPaths,
			TWithAuth
		>
		/**
		 * businesses client implementation.
		 */
		this.businesses = createClientMaybeAuth<
			BusinessesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			BusinessesPaths,
			TWithAuth
		>
		/**
		 * calendars client implementation.
		 */
		this.calendars = createClientMaybeAuth<
			CalendarsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CalendarsPaths,
			TWithAuth
		>
		/**
		 * campaigns client implementation.
		 */
		this.campaigns = createClientMaybeAuth<
			CampaignsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CampaignsPaths,
			TWithAuth
		>
		/**
		 * companies client implementation.
		 */
		this.companies = createClientMaybeAuth<
			CompaniesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CompaniesPaths,
			TWithAuth
		>
		/**
		 * contacts client implementation.
		 */
		this.contacts = createClientMaybeAuth<
			ContactsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ContactsPaths,
			TWithAuth
		>
		/**
		 * conversationAi client implementation.
		 */
		this.conversationAi = createClientMaybeAuth<
			ConversationAiPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ConversationAiPaths,
			TWithAuth
		>
		/**
		 * conversations client implementation.
		 */
		this.conversations = createClientMaybeAuth<
			ConversationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ConversationsPaths,
			TWithAuth
		>
		/**
		 * courses client implementation.
		 */
		this.courses = createClientMaybeAuth<
			CoursesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CoursesPaths,
			TWithAuth
		>
		/**
		 * customFields client implementation.
		 */
		this.customFields = createClientMaybeAuth<
			CustomFieldsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CustomFieldsPaths,
			TWithAuth
		>
		/**
		 * customMenus client implementation.
		 */
		this.customMenus = createClientMaybeAuth<
			CustomMenusPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			CustomMenusPaths,
			TWithAuth
		>
		/**
		 * emailIsv client implementation.
		 */
		this.emailIsv = createClientMaybeAuth<
			EmailIsvPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			EmailIsvPaths,
			TWithAuth
		>
		/**
		 * emails client implementation.
		 */
		this.emails = createClientMaybeAuth<
			EmailsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			EmailsPaths,
			TWithAuth
		>
		/**
		 * forms client implementation.
		 */
		this.forms = createClientMaybeAuth<
			FormsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			FormsPaths,
			TWithAuth
		>
		/**
		 * funnels client implementation.
		 */
		this.funnels = createClientMaybeAuth<
			FunnelsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			FunnelsPaths,
			TWithAuth
		>
		/**
		 * invoices client implementation.
		 */
		this.invoices = createClientMaybeAuth<
			InvoicesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			InvoicesPaths,
			TWithAuth
		>
		/**
		 * knowledgeBase client implementation.
		 */
		this.knowledgeBase = createClientMaybeAuth<
			KnowledgeBasePaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			KnowledgeBasePaths,
			TWithAuth
		>
		/**
		 * links client implementation.
		 */
		this.links = createClientMaybeAuth<
			LinksPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			LinksPaths,
			TWithAuth
		>
		/**
		 * locations client implementation.
		 */
		this.locations = createClientMaybeAuth<
			LocationsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			LocationsPaths,
			TWithAuth
		>
		/**
		 * marketplace client implementation.
		 */
		this.marketplace = createClientMaybeAuth<
			MarketplacePaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			MarketplacePaths,
			TWithAuth
		>
		/**
		 * medias client implementation.
		 */
		this.medias = createClientMaybeAuth<
			MediasPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			MediasPaths,
			TWithAuth
		>
		/**
		 * objects client implementation.
		 */
		this.objects = createClientMaybeAuth<
			ObjectsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ObjectsPaths,
			TWithAuth
		>
		/**
		 * opportunities client implementation.
		 */
		this.opportunities = createClientMaybeAuth<
			OpportunitiesPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			OpportunitiesPaths,
			TWithAuth
		>
		/**
		 * payments client implementation.
		 */
		this.payments = createClientMaybeAuth<
			PaymentsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			PaymentsPaths,
			TWithAuth
		>
		/**
		 * phoneSystem client implementation.
		 */
		this.phoneSystem = createClientMaybeAuth<
			PhoneSystemPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			PhoneSystemPaths,
			TWithAuth
		>
		/**
		 * products client implementation.
		 */
		this.products = createClientMaybeAuth<
			ProductsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ProductsPaths,
			TWithAuth
		>
		/**
		 * proposals client implementation.
		 */
		this.proposals = createClientMaybeAuth<
			ProposalsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			ProposalsPaths,
			TWithAuth
		>
		/**
		 * saasApi client implementation.
		 */
		this.saasApi = createClientMaybeAuth<
			SaasApiPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			SaasApiPaths,
			TWithAuth
		>
		/**
		 * snapshots client implementation.
		 */
		this.snapshots = createClientMaybeAuth<
			SnapshotsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			SnapshotsPaths,
			TWithAuth
		>
		/**
		 * socialMediaPosting client implementation.
		 */
		this.socialMediaPosting = createClientMaybeAuth<
			SocialMediaPostingPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			SocialMediaPostingPaths,
			TWithAuth
		>
		/**
		 * store client implementation.
		 */
		this.store = createClientMaybeAuth<
			StorePaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			StorePaths,
			TWithAuth
		>
		/**
		 * surveys client implementation.
		 */
		this.surveys = createClientMaybeAuth<
			SurveysPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			SurveysPaths,
			TWithAuth
		>
		/**
		 * users client implementation.
		 */
		this.users = createClientMaybeAuth<
			UsersPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			UsersPaths,
			TWithAuth
		>
		/**
		 * voiceAi client implementation.
		 */
		this.voiceAi = createClientMaybeAuth<
			VoiceAiPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			VoiceAiPaths,
			TWithAuth
		>
		/**
		 * workflows client implementation.
		 */
		this.workflows = createClientMaybeAuth<
			WorkflowsPaths,
			AUTH_HEADERS | undefined
		>(authHeaders, this._clientConfig) as ClientForAuth<
			WorkflowsPaths,
			TWithAuth
		>
	}
}
