// This file is generated by the generate-interface.ts script.
// Do not edit directly.

import type { paths as SocialMediaPostingPaths } from '../types/social-media-posting'
import type { paths as FunnelsPaths } from '../types/funnels'
import type { paths as ProposalsPaths } from '../types/proposals'
import type { paths as ObjectsPaths } from '../types/objects'
import type { paths as CampaignsPaths } from '../types/campaigns'
import type { paths as BlogsPaths } from '../types/blogs'
import type { paths as MarketplacePaths } from '../types/marketplace'
import type { paths as CustomFieldsPaths } from '../types/custom-fields'
import type { paths as AgenciesPaths } from '../types/agencies'
import type { paths as BusinessesPaths } from '../types/businesses'
import type { paths as EmailIsvPaths } from '../types/email-isv'
import type { paths as CalendarsPaths } from '../types/calendars'
import type { paths as UsersPaths } from '../types/users'
import type { paths as PhoneSystemPaths } from '../types/phone-system'
import type { paths as ProductsPaths } from '../types/products'
import type { paths as StorePaths } from '../types/store'
import type { paths as ContactsPaths } from '../types/contacts'
import type { paths as LocationsPaths } from '../types/locations'
import type { paths as AssociationsPaths } from '../types/associations'
import type { paths as LinksPaths } from '../types/links'
import type { paths as PaymentsPaths } from '../types/payments'
import type { paths as WorkflowsPaths } from '../types/workflows'
import type { paths as ConversationsPaths } from '../types/conversations'
import type { paths as SnapshotsPaths } from '../types/snapshots'
import type { paths as OpportunitiesPaths } from '../types/opportunities'
import type { paths as SaasApiPaths } from '../types/saas-api'
import type { paths as VoiceAiPaths } from '../types/voice-ai'
import type { paths as EmailsPaths } from '../types/emails'
import type { paths as CompaniesPaths } from '../types/companies'
import type { paths as FormsPaths } from '../types/forms'
import type { paths as CustomMenusPaths } from '../types/custom-menus'
import type { paths as CoursesPaths } from '../types/courses'
import type { paths as MediasPaths } from '../types/medias'
import type { paths as SurveysPaths } from '../types/surveys'
import type { paths as InvoicesPaths } from '../types/invoices'

import type { Client } from 'openapi-fetch'
import type { AccessType } from '../scopes/scope-types'
import type { ClientWithAuth } from './types'
import type { HighLevelClientConfig } from './default'
import type { DefaultOauthClient, OauthClientImpl } from '../oauth/impl'

export interface HighLevelClientInterface<
	T extends AccessType,
	TOAuth extends DefaultOauthClient | OauthClientImpl<T>,
> {
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth
	socialMediaPosting:
		| Client<SocialMediaPostingPaths>
		| ClientWithAuth<SocialMediaPostingPaths>
	funnels: Client<FunnelsPaths> | ClientWithAuth<FunnelsPaths>
	proposals: Client<ProposalsPaths> | ClientWithAuth<ProposalsPaths>
	objects: Client<ObjectsPaths> | ClientWithAuth<ObjectsPaths>
	campaigns: Client<CampaignsPaths> | ClientWithAuth<CampaignsPaths>
	blogs: Client<BlogsPaths> | ClientWithAuth<BlogsPaths>
	marketplace: Client<MarketplacePaths> | ClientWithAuth<MarketplacePaths>
	customFields: Client<CustomFieldsPaths> | ClientWithAuth<CustomFieldsPaths>
	agencies: Client<AgenciesPaths> | ClientWithAuth<AgenciesPaths>
	businesses: Client<BusinessesPaths> | ClientWithAuth<BusinessesPaths>
	emailIsv: Client<EmailIsvPaths> | ClientWithAuth<EmailIsvPaths>
	calendars: Client<CalendarsPaths> | ClientWithAuth<CalendarsPaths>
	users: Client<UsersPaths> | ClientWithAuth<UsersPaths>
	phoneSystem: Client<PhoneSystemPaths> | ClientWithAuth<PhoneSystemPaths>
	products: Client<ProductsPaths> | ClientWithAuth<ProductsPaths>
	store: Client<StorePaths> | ClientWithAuth<StorePaths>
	contacts: Client<ContactsPaths> | ClientWithAuth<ContactsPaths>
	locations: Client<LocationsPaths> | ClientWithAuth<LocationsPaths>
	associations: Client<AssociationsPaths> | ClientWithAuth<AssociationsPaths>
	links: Client<LinksPaths> | ClientWithAuth<LinksPaths>
	payments: Client<PaymentsPaths> | ClientWithAuth<PaymentsPaths>
	workflows: Client<WorkflowsPaths> | ClientWithAuth<WorkflowsPaths>
	conversations:
		| Client<ConversationsPaths>
		| ClientWithAuth<ConversationsPaths>
	snapshots: Client<SnapshotsPaths> | ClientWithAuth<SnapshotsPaths>
	opportunities:
		| Client<OpportunitiesPaths>
		| ClientWithAuth<OpportunitiesPaths>
	saasApi: Client<SaasApiPaths> | ClientWithAuth<SaasApiPaths>
	voiceAi: Client<VoiceAiPaths> | ClientWithAuth<VoiceAiPaths>
	emails: Client<EmailsPaths> | ClientWithAuth<EmailsPaths>
	companies: Client<CompaniesPaths> | ClientWithAuth<CompaniesPaths>
	forms: Client<FormsPaths> | ClientWithAuth<FormsPaths>
	customMenus: Client<CustomMenusPaths> | ClientWithAuth<CustomMenusPaths>
	courses: Client<CoursesPaths> | ClientWithAuth<CoursesPaths>
	medias: Client<MediasPaths> | ClientWithAuth<MediasPaths>
	surveys: Client<SurveysPaths> | ClientWithAuth<SurveysPaths>
	invoices: Client<InvoicesPaths> | ClientWithAuth<InvoicesPaths>
}
