// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface AppInstall {
	type?: string
	appId?: string
	companyId?: string
	locationId?: string
	userId?: string
	planId?: string
	trial?: {
		onTrial?: boolean
		trialDuration?: number
		trialStartDate?: {
			[k: string]: unknown | undefined
		}
		[k: string]: unknown | undefined
	}
	isWhitelabelCompany?: boolean
	whitelabelDetails?: {
		domain?: string
		logoUrl?: string
		[k: string]: unknown | undefined
	}
	companyName?: string
	[k: string]: unknown | undefined
}
