// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface AppointmentUpdate {
type?: string
locationId?: string
appointment?: {
id?: string
address?: string
title?: string
calendarId?: string
contactId?: string
groupId?: string
appointmentStatus?: string
assignedUserId?: string
users?: unknown[]
notes?: string
source?: string
startTime?: string
endTime?: string
dateAdded?: string
dateUpdated?: string
[k: string]: unknown | undefined
}
[k: string]: unknown | undefined
}
