// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface AppUninstall {
type?: string
appId?: string
companyId?: string
locationId?: string
[k: string]: unknown | undefined
}
