// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface AssociationUpdate {
id?: string
associationType?: string
firstObjectKey?: string
firstObjectLabel?: string
firstObjectToSecondObjectCardinality?: string
secondObjectKey?: string
secondObjectLabel?: string
secondObjectToFirstObjectCardinality?: string
key?: string
locationId?: string
[k: string]: unknown | undefined
}
