// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface AssociationCreate {
	id?: string
	associationType?: string
	firstObjectKey?: string
	firstObjectLabel?: string
	secondObjectKey?: string
	secondObjectLabel?: string
	key?: string
	locationId?: string
	[k: string]: unknown | undefined
}
