// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface CampaignStatusUpdate {
	type?: string
	locationId?: string
	id?: string
	contactId?: string
	status?: string
	templateId?: string
	replied?: string
	dateAdded?: string
	[k: string]: unknown | undefined
}
