// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface ContactDndUpdate {
type?: string
locationId?: string
id?: string
address1?: string
city?: string
companyName?: string
country?: string
source?: string
dateAdded?: string
dateOfBirth?: string
dnd?: boolean
dndSettings?: {
SMS?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
Email?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
GMB?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
FB?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
WhatsApp?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
Call?: {
status?: string
message?: string
code?: string
[k: string]: unknown | undefined
}
[k: string]: unknown | undefined
}
email?: string
name?: string
firstName?: string
lastName?: string
phone?: string
postalCode?: string
state?: string
tags?: unknown[]
website?: string
attachments?: unknown[]
assignedTo?: string
customFields?: {
id?: string
value?: (string | number | unknown[] | {
[k: string]: unknown | undefined
})
[k: string]: unknown | undefined
}[]
[k: string]: unknown | undefined
}
