// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface ConversationUnreadWebhook {
	type?: string
	locationId?: string
	id?: string
	contactId?: string
	unreadCount?: number
	inbox?: boolean
	starred?: boolean
	deleted?: boolean
	[k: string]: unknown | undefined
}
