// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface InvoiceDelete {
	_id?: string
	status?: string
	liveMode?: boolean
	amountPaid?: number
	altId?: string
	altType?: string
	name?: string
	businessDetails?: {
		name?: string
		address?: string
		phoneNo?: string
		website?: string
		logoUrl?: string
		customValues?: string[]
		[k: string]: unknown | undefined
	}
	invoiceNumber?: string
	currency?: string
	contactDetails?: {
		id?: string
		phoneNo?: string
		email?: string
		customFields?: string[]
		name?: string
		address?: {
			countryCode?: string
			addressLine1?: string
			addressLine2?: string
			city?: string
			state?: string
			postalCode?: string
			[k: string]: unknown | undefined
		}
		additionalEmails?: {
			email?: string
			[k: string]: unknown | undefined
		}[]
		companyName?: string
		[k: string]: unknown | undefined
	}
	issueDate?: string
	dueDate?: string
	discount?: {
		type?: string
		value?: number
		[k: string]: unknown | undefined
	}
	invoiceItems?: {
		taxes?: unknown[]
		_id?: string
		productId?: string
		priceId?: string
		currency?: string
		name?: string
		qty?: number
		amount?: number
		[k: string]: unknown | undefined
	}[]
	total?: number
	title?: string
	amountDue?: number
	createdAt?: string
	updatedAt?: string
	totalSummary?: {
		subTotal?: number
		discount?: number
		[k: string]: unknown | undefined
	}
	[k: string]: unknown | undefined
}
