// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface LCEmailStats {
	type?: string
	locationId?: string
	companyId?: string
	webhookPayload?: {
		event?: string
		id?: string
		timestamp?: number
		flags?: {
			'is-authenticated'?: boolean
			'is-routed'?: boolean
			'is-big'?: boolean
			'is-system-test'?: boolean
			'is-test-mode'?: boolean
			[k: string]: unknown | undefined
		}
		message?: {
			attachments?: unknown[]
			headers?: {
				'message-id'?: string
				from?: string
				to?: string
				[k: string]: unknown | undefined
			}
			size?: number
			[k: string]: unknown | undefined
		}
		'log-level'?: string
		recipient?: string
		'recipient-domain'?: string
		tags?: unknown[]
		'recipient-provider'?: string
		campaigns?: unknown[]
		'delivery-status'?: {
			'attempt-no'?: number
			code?: number
			message?: string
			description?: string
			'session-seconds'?: number
			'enhanced-code'?: string
			'mx-host'?: string
			utf8?: boolean
			'i-first-delivery-attempt-seconds'?: number
			[k: string]: unknown | undefined
		}
		envelope?: {
			sender?: string
			targets?: string
			transport?: string
			'sending-ip'?: string
			'i-ip-pool-id'?: string
			'i-ip-pool-name'?: string
			[k: string]: unknown | undefined
		}
		[k: string]: unknown | undefined
	}
	[k: string]: unknown | undefined
}
