// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface LocationUpdate {
type?: string
id?: string
name?: string
email?: string
stripeProductId?: string
companyId?: string
[k: string]: unknown | undefined
}
