// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface NoteCreate {
	type?: string
	locationId?: string
	id?: string
	body?: string
	contactId?: string
	dateAdded?: string
	[k: string]: unknown | undefined
}
