// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface ObjectSchemaCreate {
	id?: string
	labels: {
		singular: string
		plural: string
	}
	description?: string
	searchableProperties?: string[]
	primaryDisplayProperty: string
	key: string
	locationId: string
	createdBy?: {
		[k: string]: unknown | undefined
	}
	updatedBy?: {
		[k: string]: unknown | undefined
	}
	createdAt?: string
	updatedAt?: string
	timestamp?: string
	objectType: ObjectType
	[k: string]: unknown | undefined
}

export enum ObjectType {
	USER_DEFINED = 'USER_DEFINED',
}
