// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface OpportunityDelete {
type?: string
locationId?: string
id?: string
assignedTo?: string
contactId?: string
monetaryValue?: number
name?: string
pipelineId?: string
pipelineStageId?: string
source?: string
status?: string
dateAdded?: string
[k: string]: unknown | undefined
}
