// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface OrderCreate {
type?: string
altId?: string
altType?: string
_id?: string
contactId?: string
contactSnapshot?: {
locationId?: string
id?: string
address1?: string
city?: string
companyName?: string
country?: string
source?: string
dateAdded?: string
dateOfBirth?: string
dnd?: boolean
email?: string
name?: string
firstName?: string
lastName?: string
phone?: string
postalCode?: string
state?: string
tags?: unknown[]
website?: string
attachments?: unknown[]
assignedTo?: string
[k: string]: unknown | undefined
}
status?: string
fulfillmentStatus?: string
currency?: string
amount?: number
liveMode?: boolean
items?: {
name?: string
qty?: number
product?: {
[k: string]: unknown | undefined
}
price?: {
[k: string]: unknown | undefined
}
[k: string]: unknown | undefined
}[]
amountSummary?: {
discount?: number
shipping?: number
subtotal?: number
tax?: number
[k: string]: unknown | undefined
}
taxSummary?: {
_id?: string
amount?: number
calculation?: string
name?: string
rate?: number
[k: string]: unknown | undefined
}[]
source?: {
id?: string
name?: string
type?: string
subType?: string
meta?: {
[k: string]: unknown | undefined
}
[k: string]: unknown | undefined
}
createdAt?: string
updatedAt?: string
[k: string]: unknown | undefined
}
