// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface OutboundMessage {
	type?: string
	locationId?: string
	attachments?: unknown[]
	body?: string
	contactId?: string
	contentType?: string
	conversationId?: string
	dateAdded?: string
	direction?: string
	messageType?: string
	status?: string
	messageId?: string
	userId?: string
	source?: string
	conversationProviderId?: string
	callDuration?: number
	callStatus?: string
	[k: string]: unknown | undefined
}
