// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface PlanChange {
	type?: string
	appId?: string
	locationId?: string
	companyId?: string
	userId?: string
	currentPlanId?: string
	newPlanId?: string
	[k: string]: unknown | undefined
}
