// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface PriceUpdate {
	_id?: string
	membershipOffers?: {
		label?: string
		value?: string
		_id?: string
		[k: string]: unknown | undefined
	}[]
	variantOptionIds?: string[]
	locationId?: string
	product?: string
	userId?: string
	name?: string
	type?: string
	currency?: string
	amount?: number
	recurring?: {
		interval?: string
		intervalCount?: number
		[k: string]: unknown | undefined
	}
	createdAt?: string
	updatedAt?: string
	compareAtPrice?: number
	trackInventory?: null
	availableQuantity?: number
	allowOutOfStockPurchases?: boolean
	[k: string]: unknown | undefined
}
