// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface ProductCreate {
	_id?: string
	description?: string
	variants?: {
		id?: string
		name?: string
		options?: {
			id?: string
			name?: string
			[k: string]: unknown | undefined
		}[]
		[k: string]: unknown | undefined
	}[]
	medias?: {
		id?: string
		title?: string
		url?: string
		type?: string
		isFeatured?: boolean
		[k: string]: unknown | undefined
	}[]
	locationId?: string
	name?: string
	productType?: string
	availableInStore?: boolean
	userId?: string
	createdAt?: string
	updatedAt?: string
	statementDescriptor?: string
	image?: string
	[k: string]: unknown | undefined
}
