// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface ProviderOutboundMessage {
contactId?: string
locationId?: string
messageId?: string
emailMessageId?: string
type?: {
[k: string]: unknown | undefined
}
attachments?: unknown[]
message?: string
phone?: string
emailTo?: string
emailFrom?: string
html?: string
subject?: string
userId?: string
[k: string]: unknown | undefined
}
