// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface RecordCreate {
type?: string
locationId?: string
owners?: string[]
followers?: string[]
properties?: {
key?: string
valueString?: string
[k: string]: unknown | undefined
}[]
id?: string
timestamp?: string
[k: string]: unknown | undefined
}
