// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

export interface RelationCreate {
	id?: string
	firstObjectKey?: string
	firstRecordId?: string
	secondObjectKey?: string
	secondRecordId?: string
	associationId?: string
	locationId?: string
	[k: string]: unknown | undefined
}
