// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export interface TaskDelete {
type?: string
locationId?: string
id?: string
assignedTo?: string
body?: string
contactId?: string
title?: string
dateAdded?: string
dueDate?: string
[k: string]: unknown | undefined
}
