// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.

export type UserUpdate = ((SubAccountUserPayload | AgencyUserPayload) & {
type: "UserUpdate"
locationId?: string
companyId?: string
id: string
firstName: string
lastName: string
email: string
phone?: string
extension?: string
role: string
permissions: {
adwordsReportingEnabled?: boolean
affiliateManagerEnabled?: boolean
agentReportingEnabled?: boolean
appointmentsEnabled?: boolean
assignedDataOnly?: boolean
attributionsReportingEnabled?: boolean
bloggingEnabled?: boolean
botService?: boolean
bulkRequestsEnabled?: boolean
campaignsEnabled?: boolean
campaignsReadOnly?: boolean
cancelSubscriptionEnabled?: boolean
communitiesEnabled?: boolean
contactsEnabled?: boolean
contentAiEnabled?: boolean
conversationsEnabled?: boolean
dashboardStatsEnabled?: boolean
facebookAdsReportingEnabled?: boolean
funnelsEnabled?: boolean
invoiceEnabled?: boolean
leadValueEnabled?: boolean
marketingEnabled?: boolean
membershipEnabled?: boolean
onlineListingsEnabled?: boolean
opportunitiesEnabled?: boolean
paymentsEnabled?: boolean
phoneCallEnabled?: boolean
recordPaymentEnabled?: boolean
refundsEnabled?: boolean
reviewsEnabled?: boolean
settingsEnabled?: boolean
socialPlanner?: boolean
tagsEnabled?: boolean
triggersEnabled?: boolean
websitesEnabled?: boolean
workflowsEnabled?: boolean
workflowsReadOnly?: boolean
[k: string]: unknown | undefined
}
scopes: string[]
locations?: string[]
[k: string]: unknown | undefined
})

export interface SubAccountUserPayload {
[k: string]: unknown | undefined
}
export interface AgencyUserPayload {
[k: string]: unknown | undefined
}
