// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

import type { AppInstall } from './AppInstall'
import type { AppointmentCreate } from './AppointmentCreate'
import type { AppointmentDelete } from './AppointmentDelete'
import type { AppointmentUpdate } from './AppointmentUpdate'
import type { AppUninstall } from './AppUninstall'
import type { AssociationCreate } from './AssociationCreate'
import type { AssociationDelete } from './AssociationDelete'
import type { AssociationUpdate } from './AssociationUpdate'
import type { CampaignStatusUpdate } from './CampaignStatusUpdate'
import type { ContactCreate } from './ContactCreate'
import type { ContactDelete } from './ContactDelete'
import type { ContactDndUpdate } from './ContactDndUpdate'
import type { ContactTagUpdate } from './ContactTagUpdate'
import type { ContactUpdate } from './ContactUpdate'
import type { ConversationUnreadWebhook } from './ConversationUnreadWebhook'
import type { InboundMessage } from './InboundMessage'
import type { InvoiceCreate } from './InvoiceCreate'
import type { InvoiceDelete } from './InvoiceDelete'
import type { InvoicePaid } from './InvoicePaid'
import type { InvoicePartiallyPaid } from './InvoicePartiallyPaid'
import type { InvoiceSent } from './InvoiceSent'
import type { InvoiceUpdate } from './InvoiceUpdate'
import type { InvoiceVoid } from './InvoiceVoid'
import type { LCEmailStats } from './LCEmailStats'
import type { LocationCreate } from './LocationCreate'
import type { LocationUpdate } from './LocationUpdate'
import type { NoteCreate } from './NoteCreate'
import type { NoteDelete } from './NoteDelete'
import type { NoteUpdate } from './NoteUpdate'
import type { ObjectSchemaCreate } from './ObjectSchemaCreate'
import type { ObjectSchemaUpdate } from './ObjectSchemaUpdate'
import type { OpportunityAssignedToUpdate } from './OpportunityAssignedToUpdate'
import type { OpportunityCreate } from './OpportunityCreate'
import type { OpportunityDelete } from './OpportunityDelete'
import type { OpportunityMonetaryValueUpdate } from './OpportunityMonetaryValueUpdate'
import type { OpportunityStageUpdate } from './OpportunityStageUpdate'
import type { OpportunityStatusUpdate } from './OpportunityStatusUpdate'
import type { OpportunityUpdate } from './OpportunityUpdate'
import type { OrderCreate } from './OrderCreate'
import type { OrderStatusUpdate } from './OrderStatusUpdate'
import type { OutboundMessage } from './OutboundMessage'
import type { PlanChange } from './PlanChange'
import type { PriceCreate } from './PriceCreate'
import type { PriceDelete } from './PriceDelete'
import type { PriceUpdate } from './PriceUpdate'
import type { ProductCreate } from './ProductCreate'
import type { ProductDelete } from './ProductDelete'
import type { ProductUpdate } from './ProductUpdate'
import type { ProviderOutboundMessage } from './ProviderOutboundMessage'
import type { RecordCreate } from './RecordCreate'
import type { RecordDelete } from './RecordDelete'
import type { RecordUpdate } from './RecordUpdate'
import type { RelationCreate } from './RelationCreate'
import type { RelationDelete } from './RelationDelete'
import type { TaskComplete } from './TaskComplete'
import type { TaskCreate } from './TaskCreate'
import type { TaskDelete } from './TaskDelete'
import type { UserCreate } from './UserCreate'
import type { UserDelete } from './UserDelete'
import type { UserUpdate } from './UserUpdate'

/**
 * Map of webhook event names to their payload types.
 * This interface provides type-safe access to webhook payloads by event name.
 */
export interface WebhookEventMap {
	AppInstall: AppInstall
	AppUninstall: AppUninstall
	AppointmentCreate: AppointmentCreate
	AppointmentDelete: AppointmentDelete
	AppointmentUpdate: AppointmentUpdate
	AssociationCreate: AssociationCreate
	AssociationDelete: AssociationDelete
	AssociationUpdate: AssociationUpdate
	CampaignStatusUpdate: CampaignStatusUpdate
	ContactCreate: ContactCreate
	ContactDelete: ContactDelete
	ContactDndUpdate: ContactDndUpdate
	ContactTagUpdate: ContactTagUpdate
	ContactUpdate: ContactUpdate
	ConversationUnreadWebhook: ConversationUnreadWebhook
	InboundMessage: InboundMessage
	InvoiceCreate: InvoiceCreate
	InvoiceDelete: InvoiceDelete
	InvoicePaid: InvoicePaid
	InvoicePartiallyPaid: InvoicePartiallyPaid
	InvoiceSent: InvoiceSent
	InvoiceUpdate: InvoiceUpdate
	InvoiceVoid: InvoiceVoid
	LCEmailStats: LCEmailStats
	LocationCreate: LocationCreate
	LocationUpdate: LocationUpdate
	NoteCreate: NoteCreate
	NoteDelete: NoteDelete
	NoteUpdate: NoteUpdate
	ObjectSchemaCreate: ObjectSchemaCreate
	ObjectSchemaUpdate: ObjectSchemaUpdate
	OpportunityAssignedToUpdate: OpportunityAssignedToUpdate
	OpportunityCreate: OpportunityCreate
	OpportunityDelete: OpportunityDelete
	OpportunityMonetaryValueUpdate: OpportunityMonetaryValueUpdate
	OpportunityStageUpdate: OpportunityStageUpdate
	OpportunityStatusUpdate: OpportunityStatusUpdate
	OpportunityUpdate: OpportunityUpdate
	OrderCreate: OrderCreate
	OrderStatusUpdate: OrderStatusUpdate
	OutboundMessage: OutboundMessage
	PlanChange: PlanChange
	PriceCreate: PriceCreate
	PriceDelete: PriceDelete
	PriceUpdate: PriceUpdate
	ProductCreate: ProductCreate
	ProductDelete: ProductDelete
	ProductUpdate: ProductUpdate
	ProviderOutboundMessage: ProviderOutboundMessage
	RecordCreate: RecordCreate
	RecordDelete: RecordDelete
	RecordUpdate: RecordUpdate
	RelationCreate: RelationCreate
	RelationDelete: RelationDelete
	TaskComplete: TaskComplete
	TaskCreate: TaskCreate
	TaskDelete: TaskDelete
	UserCreate: UserCreate
	UserDelete: UserDelete
	UserUpdate: UserUpdate
}
