export const accessMap = [
	{
		endpoint: '/invoices/',
		operationId: 'list-invoices',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/',
		operationId: 'create-invoice',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/generate-invoice-number',
		operationId: 'generate-invoice-number',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule',
		operationId: 'list-invoice-schedules',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule',
		operationId: 'create-invoice-schedule',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}',
		operationId: 'delete-invoice-schedule',
		method: 'delete',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}',
		operationId: 'get-invoice-schedule',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}',
		operationId: 'update-invoice-schedule',
		method: 'put',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}/auto-payment',
		operationId: 'auto-payment-invoice-schedule',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}/cancel',
		operationId: 'cancel-invoice-schedule',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/schedule/{scheduleId}/schedule',
		operationId: 'schedule-invoice-schedule',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/template',
		operationId: 'list-invoice-templates',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/template',
		operationId: 'create-invoice-template',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/template/{templateId}',
		operationId: 'delete-invoice-template',
		method: 'delete',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/template/{templateId}',
		operationId: 'get-invoice-template',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/template/{templateId}',
		operationId: 'update-invoice-template',
		method: 'put',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/text2pay',
		operationId: 'text2pay-invoice',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/invoices/{invoiceId}',
		operationId: 'delete-invoice',
		method: 'delete',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/{invoiceId}',
		operationId: 'get-invoice',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/{invoiceId}',
		operationId: 'update-invoice',
		method: 'put',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/{invoiceId}/record-payment',
		operationId: 'record-invoice',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/{invoiceId}/send',
		operationId: 'send-invoice',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/invoices/{invoiceId}/void',
		operationId: 'void-invoice',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/social-media-posting/oauth/facebook/start',
		operationId: 'start-facebook-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/google/start',
		operationId: 'start-google-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/instagram/start',
		operationId: 'start-instagram-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/linkedin/start',
		operationId: 'start-linkedin-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/tiktok-business/start',
		operationId: 'start-tiktok-business-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/tiktok/start',
		operationId: 'start-tiktok-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/oauth/twitter/start',
		operationId: 'start-twitter-oauth',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/facebook/accounts/{accountId}',
		operationId: 'get-facebook-page-group',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/facebook/accounts/{accountId}',
		operationId: 'attach-facebook-page-group',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/google/locations/{accountId}',
		operationId: 'get-google-locations',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/google/locations/{accountId}',
		operationId: 'set-google-locations',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/instagram/accounts/{accountId}',
		operationId: 'get-instagram-page-group',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/instagram/accounts/{accountId}',
		operationId: 'attach-instagram-page-group',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/linkedin/accounts/{accountId}',
		operationId: 'get-linkedin-page-profile',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/linkedin/accounts/{accountId}',
		operationId: 'attach-linkedin-page-profile',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/tiktok-business/accounts/{accountId}',
		operationId: 'get-tiktok-business-profile',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/tiktok/accounts/{accountId}',
		operationId: 'get-tiktok-profile',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/tiktok/accounts/{accountId}',
		operationId: 'attach-tiktok-profile',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/twitter/accounts/{accountId}',
		operationId: 'get-twitter-profile',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/social-media-posting/oauth/{locationId}/twitter/accounts/{accountId}',
		operationId: 'attach-twitter-profile',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/accounts',
		operationId: 'get-account',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/accounts/{id}',
		operationId: 'delete-account',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/categories',
		operationId: 'get-categories-location-id',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/categories/{id}',
		operationId: 'get-categories-id',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv',
		operationId: 'get-upload-status',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv',
		operationId: 'upload-csv',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv/{csvId}/post/{postId}',
		operationId: 'delete-csv-post',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv/{id}',
		operationId: 'delete-csv',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv/{id}',
		operationId: 'get-csv-post',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/csv/{id}',
		operationId: 'start-csv-finalize',
		method: 'patch',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/posts',
		operationId: 'create-post',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/posts/list',
		operationId: 'get-posts',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/posts/{id}',
		operationId: 'delete-post',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/posts/{id}',
		operationId: 'get-post',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/posts/{id}',
		operationId: 'edit-post',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/set-accounts',
		operationId: 'set-accounts',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/tags',
		operationId: 'get-tags-location-id',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/social-media-posting/{locationId}/tags/details',
		operationId: 'get-tags-by-ids',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/',
		operationId: 'create-opportunity',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/pipelines',
		operationId: 'get-pipelines',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/search',
		operationId: 'search-opportunity',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/upsert',
		operationId: 'Upsert-opportunity',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}',
		operationId: 'delete-opportunity',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}',
		operationId: 'get-opportunity',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}',
		operationId: 'update-opportunity',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}/followers',
		operationId: 'remove-followers-opportunity',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}/followers',
		operationId: 'add-followers-opportunity',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/opportunities/{id}/status',
		operationId: 'update-opportunity-status',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/campaigns/',
		operationId: 'get-campaigns',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/businesses/',
		operationId: 'get-businesses-by-location',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/businesses/',
		operationId: 'create-business',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/businesses/{businessId}',
		operationId: 'delete-Business',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/businesses/{businessId}',
		operationId: 'get-business',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/businesses/{businessId}',
		operationId: 'update-business',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/',
		operationId: 'create-conversation',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/conversations/locations/{locationId}/messages/{messageId}/transcription',
		operationId: 'get-message-transcription',
		method: 'get',
		accessTypes: ['Private', 'Sub-Account'],
	},
	{
		endpoint:
			'/conversations/locations/{locationId}/messages/{messageId}/transcription/download',
		operationId: 'download-message-transcription',
		method: 'get',
		accessTypes: ['Private', 'Sub-Account'],
	},
	{
		endpoint: '/conversations/messages',
		operationId: 'send-a-new-message',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/messages/email/{emailMessageId}/schedule',
		operationId: 'cancel-scheduled-email-message',
		method: 'delete',
		accessTypes: [],
	},
	{
		endpoint: '/conversations/messages/email/{id}',
		operationId: 'get-email-by-id',
		method: 'get',
		accessTypes: [],
	},
	{
		endpoint: '/conversations/messages/inbound',
		operationId: 'add-an-inbound-message',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/messages/outbound',
		operationId: 'add-an-outbound-message',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/messages/upload',
		operationId: 'upload-file-attachments',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/messages/{id}',
		operationId: 'get-message',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint:
			'/conversations/messages/{messageId}/locations/{locationId}/recording',
		operationId: 'get-message-recording',
		method: 'get',
		accessTypes: ['Private', 'Sub-Account'],
	},
	{
		endpoint: '/conversations/messages/{messageId}/schedule',
		operationId: 'cancel-scheduled-message',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/messages/{messageId}/status',
		operationId: 'update-message-status',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/search',
		operationId: 'search-conversation',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/{conversationId}',
		operationId: 'delete-conversation',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/{conversationId}',
		operationId: 'get-conversation',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/{conversationId}',
		operationId: 'update-conversation',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/conversations/{conversationId}/messages',
		operationId: 'get-messages',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/products/',
		operationId: 'list-invoices',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/',
		operationId: 'create-product',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}',
		operationId: 'delete-product-by-id',
		method: 'delete',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}',
		operationId: 'get-product-by-id',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}',
		operationId: 'update-product-by-id',
		method: 'put',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}/price',
		operationId: 'list-prices-for-product',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}/price',
		operationId: 'create-price-for-product',
		method: 'post',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}/price/{priceId}',
		operationId: 'delete-price-by-id-for-product',
		method: 'delete',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}/price/{priceId}',
		operationId: 'get-price-by-id-for-product',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/products/{productId}/price/{priceId}',
		operationId: 'update-price-by-id-for-product',
		method: 'put',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/courses/courses-exporter/public/import',
		operationId: 'import-courses',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/surveys/',
		operationId: 'get-surveys',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/surveys/submissions',
		operationId: 'get-surveys-submissions',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/payments/custom-provider/connect',
		operationId: 'fetch-config',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/custom-provider/connect',
		operationId: 'create-config',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/custom-provider/disconnect',
		operationId: 'disconnect-config',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/custom-provider/provider',
		operationId: 'create-integration_delete',
		method: 'delete',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/custom-provider/provider',
		operationId: 'create-integration',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/integrations/provider/whitelabel',
		operationId: 'list-integration-providers',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/integrations/provider/whitelabel',
		operationId: 'create-integration provider',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/orders',
		operationId: 'list-orders',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/orders/{orderId}',
		operationId: 'get-order-by-id',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/orders/{orderId}/fulfillments',
		operationId: 'list-order-fulfillment',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/orders/{orderId}/fulfillments',
		operationId: 'create-order-fulfillment',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/subscriptions',
		operationId: 'list-subscriptions',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/subscriptions/{subscriptionId}',
		operationId: 'get-subscription-by-id',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/transactions',
		operationId: 'list-transactions',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/payments/transactions/{transactionId}',
		operationId: 'get-transaction-by-id',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/oauth/installedLocations',
		operationId: 'get-installed-location',
		method: 'get',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/oauth/locationToken',
		operationId: 'get-location-access-token',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/oauth/token',
		operationId: 'get-access-token',
		method: 'post',
		accessTypes: [],
	},
	{
		endpoint: '/workflows/',
		operationId: 'get-workflow',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/snapshots/',
		operationId: 'get-custom-snapshots',
		method: 'get',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/snapshots/share/link',
		operationId: 'create-snapshot-share-link',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/snapshots/snapshot-status/{snapshotId}',
		operationId: 'get-snapshot-push',
		method: 'get',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/snapshots/snapshot-status/{snapshotId}/location/{locationId}',
		operationId: 'get-latest-snapshot-push',
		method: 'get',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/bulk-disable-saas/{companyId}',
		operationId: 'bulk-disable-saas',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/enable-saas/{locationId}',
		operationId: 'enable-saas',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/locations',
		operationId: 'locations',
		method: 'get',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/pause/{locationId}',
		operationId: 'pause-location',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/update-rebilling/{companyId}',
		operationId: 'update-rebilling',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/saas-api/public-api/update-saas-subscription/{locationId}',
		operationId: 'generate-payment-link',
		method: 'put',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/users/',
		operationId: 'get-user-by-location',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/users/',
		operationId: 'create-user',
		method: 'post',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/users/search',
		operationId: 'search-users',
		method: 'get',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/users/{userId}',
		operationId: 'delete-user',
		method: 'delete',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/users/{userId}',
		operationId: 'get-user',
		method: 'get',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/users/{userId}',
		operationId: 'update-user',
		method: 'put',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/funnels/funnel/list',
		operationId: 'getFunnels',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/funnels/lookup/redirect',
		operationId: 'create-redirect',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/funnels/lookup/redirect/list',
		operationId: 'fetch-redirects-list',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/funnels/lookup/redirect/{id}',
		operationId: 'delete-redirect-by-id',
		method: 'delete',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/funnels/lookup/redirect/{id}',
		operationId: 'update-redirect-by-id',
		method: 'patch',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/funnels/page',
		operationId: 'getPagesByFunnelId',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/locations/',
		operationId: 'create-location',
		method: 'post',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/locations/search',
		operationId: 'search-locations',
		method: 'get',
		accessTypes: ['Agency', 'Sub-Account'],
	},
	{
		endpoint: '/locations/{locationId}',
		operationId: 'delete-location',
		method: 'delete',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/locations/{locationId}',
		operationId: 'get-location',
		method: 'get',
		accessTypes: ['Sub-Account', 'Agency'],
	},
	{
		endpoint: '/locations/{locationId}',
		operationId: 'put-location',
		method: 'put',
		accessTypes: ['Agency'],
	},
	{
		endpoint: '/locations/{locationId}/customFields',
		operationId: 'get-custom-fields',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customFields',
		operationId: 'create-custom-field',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customFields/upload',
		operationId: 'upload-file-customFields',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customFields/{id}',
		operationId: 'delete-custom-field',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customFields/{id}',
		operationId: 'get-custom-field',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customFields/{id}',
		operationId: 'update-custom-field',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customValues',
		operationId: 'get-custom-values',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customValues',
		operationId: 'create-custom-value',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customValues/{id}',
		operationId: 'delete-custom-value',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customValues/{id}',
		operationId: 'get-custom-value',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/customValues/{id}',
		operationId: 'update-custom-value',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tags',
		operationId: 'get-location-tags',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tags',
		operationId: 'create-tag',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tags/{tagId}',
		operationId: 'delete-tag',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tags/{tagId}',
		operationId: 'get-tag-by-id',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tags/{tagId}',
		operationId: 'update-tag',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/tasks/search',
		operationId: 'task-search',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/templates',
		operationId: 'GET-all-or-email-sms-templates',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/templates/{id}',
		operationId: 'DELETE-an-email-sms-template',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/locations/{locationId}/timezones',
		operationId: 'get-timezones',
		method: 'get',
		accessTypes: ['Private', 'Sub-Account'],
	},
	{
		endpoint: '/links/',
		operationId: 'get-links',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/links/',
		operationId: 'create-link',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/links/{linkId}',
		operationId: 'delete-link',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/links/{linkId}',
		operationId: 'update-link',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/companies/{companyId}',
		operationId: 'get-company',
		method: 'get',
		accessTypes: ['Private', 'Agency'],
	},
	{
		endpoint: '/contacts/',
		operationId: 'get-contacts',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/',
		operationId: 'create-contact',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/bulk/business',
		operationId: 'add-remove-contact-from-business',
		method: 'post',
		accessTypes: [],
	},
	{
		endpoint: '/contacts/business/{businessId}',
		operationId: 'get-contacts-by-businessId',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/search',
		operationId: 'search-contacts-advanced',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/search/duplicate',
		operationId: 'get-duplicate-contact',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/upsert',
		operationId: 'upsert-contact',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}',
		operationId: 'delete-contact',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}',
		operationId: 'get-contact',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}',
		operationId: 'update-contact',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/appointments',
		operationId: 'get-appointments-for-contact',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/campaigns/removeAll',
		operationId: 'remove-contact-from-every-campaign',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/campaigns/{campaignId}',
		operationId: 'remove-contact-from-campaign',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/campaigns/{campaignId}',
		operationId: 'add-contact-to-campaign',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/followers',
		operationId: 'remove-followers-contact',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/followers',
		operationId: 'add-followers-contact',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/notes',
		operationId: 'get-all-notes',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/notes',
		operationId: 'create-note',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/notes/{id}',
		operationId: 'delete-note',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/notes/{id}',
		operationId: 'get-note',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/notes/{id}',
		operationId: 'update-note',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tags',
		operationId: 'remove-tags',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tags',
		operationId: 'add-tags',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks',
		operationId: 'get-all-tasks',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks',
		operationId: 'create-task',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks/{taskId}',
		operationId: 'delete-task',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks/{taskId}',
		operationId: 'get-task',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks/{taskId}',
		operationId: 'update-task',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/tasks/{taskId}/completed',
		operationId: 'update-task-completed',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/workflow/{workflowId}',
		operationId: 'delete-contact-to-workflow',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/contacts/{contactId}/workflow/{workflowId}',
		operationId: 'add-contact-to-workflow',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/forms/',
		operationId: 'get-forms',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/forms/submissions',
		operationId: 'get-forms-submissions',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/forms/upload-custom-files',
		operationId: 'upload-to-custom-fields',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/',
		operationId: 'get-calendars',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/',
		operationId: 'create-calendar',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/blocked-slots',
		operationId: 'get-blocked-slots',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events',
		operationId: 'get-calendar-events',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/appointments',
		operationId: 'create-appointment',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/appointments/{eventId}',
		operationId: 'get-appointment',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/appointments/{eventId}',
		operationId: 'edit-appointment',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/block-slots',
		operationId: 'create-block-slot',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/block-slots/{eventId}',
		operationId: 'edit-block-slot',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/events/{eventId}',
		operationId: 'delete-event',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups',
		operationId: 'get-groups',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups',
		operationId: 'create-calendar-group',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups/validate-slug',
		operationId: 'validate-groups-slug',
		method: 'post',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups/{groupId}',
		operationId: 'delete-group',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups/{groupId}',
		operationId: 'edit-group',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/groups/{groupId}/status',
		operationId: 'disable-group',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/resources/{resourceType}',
		operationId: 'fetch-calendar-resources',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/calendars/resources/{resourceType}',
		operationId: 'create-calendar-resource',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/calendars/resources/{resourceType}/{id}',
		operationId: 'delete-calendar-resource',
		method: 'delete',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/calendars/resources/{resourceType}/{id}',
		operationId: 'get-calendar-resource',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/calendars/resources/{resourceType}/{id}',
		operationId: 'update-calendar-resource',
		method: 'put',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/calendars/{calendarId}',
		operationId: 'delete-calendar',
		method: 'delete',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/{calendarId}',
		operationId: 'get-calendar',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/{calendarId}',
		operationId: 'update-calendar',
		method: 'put',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/calendars/{calendarId}/free-slots',
		operationId: 'get-slots',
		method: 'get',
		accessTypes: ['Private'],
	},
	{
		endpoint: '/medias/files',
		operationId: 'fetch-media-content',
		method: 'get',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/medias/upload-file',
		operationId: 'upload-media-content',
		method: 'post',
		accessTypes: ['Sub-Account'],
	},
	{
		endpoint: '/medias/{id}',
		operationId: 'delete-media-content',
		method: 'delete',
		accessTypes: ['Sub-Account'],
	},
] as const
