import type { components } from './webhooks-openapi'

type WebhooksOpenAPI = components['schemas']

export type AppointmentCreate = WebhooksOpenAPI['AppointmentCreate']
export type AppointmentDelete = WebhooksOpenAPI['AppointmentDelete']
export type AppUninstall = WebhooksOpenAPI['AppUninstall']
export type AppInstall = WebhooksOpenAPI['AppInstall']
export type AppointmentUpdate = WebhooksOpenAPI['AppointmentUpdate']
export type CampaignStatusUpdate = WebhooksOpenAPI['CampaignStatusUpdate']
export type ContactDelete = WebhooksOpenAPI['ContactDelete']
export type ContactDndUpdate = WebhooksOpenAPI['ContactDndUpdate']
export type ContactCreate = WebhooksOpenAPI['ContactCreate']
export type ContactTagUpdate = WebhooksOpenAPI['ContactTagUpdate']
export type ContactUpdate = WebhooksOpenAPI['ContactUpdate']
export type InboundMessage = WebhooksOpenAPI['InboundMessage']
export type ConversationUnreadWebhook =
	WebhooksOpenAPI['ConversationUnreadWebhook']
export type InvoiceCreate = WebhooksOpenAPI['InvoiceCreate']
export type InvoiceVoid = WebhooksOpenAPI['InvoiceVoid']
export type InvoiceSent = WebhooksOpenAPI['InvoiceSent']
export type ConversationProviderOutboundWebhook =
	WebhooksOpenAPI['ConversationProviderOutboundWebhook']
export type InvoicePartiallyPaid = WebhooksOpenAPI['InvoicePartiallyPaid']
export type InvoiceDelete = WebhooksOpenAPI['InvoiceDelete']
export type InvoicePaid = WebhooksOpenAPI['InvoicePaid']
export type InvoiceUpdate = WebhooksOpenAPI['InvoiceUpdate']
export type LCEmailStats = WebhooksOpenAPI['LCEmailStats']
export type LocationUpdate = WebhooksOpenAPI['LocationUpdate']
export type NoteCreate = WebhooksOpenAPI['NoteCreate']
export type NoteDelete = WebhooksOpenAPI['NoteDelete']
export type OpportunityAssignedToUpdate =
	WebhooksOpenAPI['OpportunityAssignedToUpdate']
export type LocationCreate = WebhooksOpenAPI['LocationCreate']
export type OpportunityCreate = WebhooksOpenAPI['OpportunityCreate']
export type OpportunityDelete = WebhooksOpenAPI['OpportunityDelete']
export type OpportunityMonetaryValueUpdate =
	WebhooksOpenAPI['OpportunityMonetaryValueUpdate']
export type NoteUpdate = WebhooksOpenAPI['NoteUpdate']
export type OpportunityStageUpdate = WebhooksOpenAPI['OpportunityStageUpdate']
export type OpportunityStatusUpdate = WebhooksOpenAPI['OpportunityStatusUpdate']
export type OrderStatusUpdate = WebhooksOpenAPI['OrderStatusUpdate']
export type OpportunityUpdate = WebhooksOpenAPI['OpportunityUpdate']
export type OrderCreate = WebhooksOpenAPI['OrderCreate']
export type OutboundMessage = WebhooksOpenAPI['OutboundMessage']
export type PriceUpdate = WebhooksOpenAPI['PriceUpdate']
export type ProductCreate = WebhooksOpenAPI['ProductCreate']
export type PriceCreate = WebhooksOpenAPI['PriceCreate']
export type ProductUpdate = WebhooksOpenAPI['ProductUpdate']
export type ProductDelete = WebhooksOpenAPI['ProductDelete']
export type PriceDelete = WebhooksOpenAPI['PriceDelete']
export type TaskComplete = WebhooksOpenAPI['TaskComplete']
export type TaskCreate = WebhooksOpenAPI['TaskCreate']
export type TaskDelete = WebhooksOpenAPI['TaskDelete']
export type UserCreate = WebhooksOpenAPI['UserCreate']
