// This file is generated by the generate-interface.ts script.
// Do not edit directly.

import type * as Businesses from '../../generated/v2/openapi/businesses'
import type * as Calendars from '../../generated/v2/openapi/calendars'
import type * as Campaigns from '../../generated/v2/openapi/campaigns'
import type * as Companies from '../../generated/v2/openapi/companies'
import type * as Contacts from '../../generated/v2/openapi/contacts'
import type * as Conversations from '../../generated/v2/openapi/conversations'
import type * as Courses from '../../generated/v2/openapi/courses'
import type * as Forms from '../../generated/v2/openapi/forms'
import type * as Funnels from '../../generated/v2/openapi/funnels'
import type * as Invoices from '../../generated/v2/openapi/invoices'
import type * as Links from '../../generated/v2/openapi/links'
import type * as Locations from '../../generated/v2/openapi/locations'
import type * as Medias from '../../generated/v2/openapi/medias'
import type * as Opportunities from '../../generated/v2/openapi/opportunities'
import type * as Payments from '../../generated/v2/openapi/payments'
import type * as Products from '../../generated/v2/openapi/products'
import type * as SaasApi from '../../generated/v2/openapi/saas-api'
import type * as Snapshots from '../../generated/v2/openapi/snapshots'
import type * as SocialMediaPosting from '../../generated/v2/openapi/social-media-posting'
import type * as Surveys from '../../generated/v2/openapi/surveys'
import type * as Users from '../../generated/v2/openapi/users'
import type * as Workflows from '../../generated/v2/openapi/workflows'

import type { Client } from 'openapi-fetch'
import type { AccessType } from '../../lib/type-utils'
import type { HighLevelClientConfig } from './base'
import type { ClientWithAuth } from './client-types'
import type { BaseOauthClient, OauthClientImpl } from './oauth/oauth-impl'

export interface HighLevelClientInterface<
	T extends AccessType,
	TOAuth extends BaseOauthClient | OauthClientImpl<T>,
> {
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth
	invoices: Client<Invoices.paths> | ClientWithAuth<Invoices.paths>
	socialMediaPosting:
		| Client<SocialMediaPosting.paths>
		| ClientWithAuth<SocialMediaPosting.paths>
	opportunities:
		| Client<Opportunities.paths>
		| ClientWithAuth<Opportunities.paths>
	campaigns: Client<Campaigns.paths> | ClientWithAuth<Campaigns.paths>
	businesses: Client<Businesses.paths> | ClientWithAuth<Businesses.paths>
	conversations:
		| Client<Conversations.paths>
		| ClientWithAuth<Conversations.paths>
	products: Client<Products.paths> | ClientWithAuth<Products.paths>
	courses: Client<Courses.paths> | ClientWithAuth<Courses.paths>
	surveys: Client<Surveys.paths> | ClientWithAuth<Surveys.paths>
	payments: Client<Payments.paths> | ClientWithAuth<Payments.paths>
	workflows: Client<Workflows.paths> | ClientWithAuth<Workflows.paths>
	snapshots: Client<Snapshots.paths> | ClientWithAuth<Snapshots.paths>
	saasApi: Client<SaasApi.paths> | ClientWithAuth<SaasApi.paths>
	users: Client<Users.paths> | ClientWithAuth<Users.paths>
	funnels: Client<Funnels.paths> | ClientWithAuth<Funnels.paths>
	locations: Client<Locations.paths> | ClientWithAuth<Locations.paths>
	links: Client<Links.paths> | ClientWithAuth<Links.paths>
	companies: Client<Companies.paths> | ClientWithAuth<Companies.paths>
	contacts: Client<Contacts.paths> | ClientWithAuth<Contacts.paths>
	forms: Client<Forms.paths> | ClientWithAuth<Forms.paths>
	calendars: Client<Calendars.paths> | ClientWithAuth<Calendars.paths>
	medias: Client<Medias.paths> | ClientWithAuth<Medias.paths>
}
