import path from 'node:path'
import kleur from 'kleur'
import { toCamelCase } from '../src/lib/utils'

if (import.meta.main) {
	const glob = new Bun.Glob('src/v2/types/*.ts')
	const typeFiles = await Array.fromAsync(
		glob.scan({ absolute: true, onlyFiles: true }),
	)
	await generateClientInterface(typeFiles)
}

export async function generateClientInterface(typeFiles: string[]) {
	// ignore oauth bc we handle it separately
	// ignore common-schemas as they are only refereenced by other files
	const IGNORE_FILES = ['oauth.ts', 'common-schemas.ts']
	const CLIENT_INTERFACE_FILE = path.join(
		process.cwd(),
		'src/v2/client/interface.ts',
	)

	const schemaFiles = typeFiles
		.filter((file) => {
			const basename = path.basename(file)
			return !IGNORE_FILES.includes(basename)
		})
		.map((file) => {
			const fileName = path.basename(file, '.ts')
			const camelName = toCamelCase(fileName)
			const pascalName = camelName.charAt(0).toUpperCase() + camelName.slice(1)
			return { pascalName, camelName, fileName }
		})

	const importStatements = schemaFiles
		.map((file) => {
			return `import type { paths as ${file.pascalName}Paths } from '../types/${file.fileName}'`
		})
		.join('\n')

	/**
	 * client interfaces for each of the v2 endpoints.
	 */
	const interfaceProperties = schemaFiles.map((file) => {
		return `${file.camelName}: Client<${file.pascalName}Paths> | ClientWithAuth<${file.pascalName}Paths>`
	})

	const interfaceContent = `
// This file is generated by the ${import.meta.file} script.
// Do not edit directly.

${importStatements}

import type { Client } from 'openapi-fetch'
import type { AccessType } from '../../lib/type-utils'
import type { ClientWithAuth } from './types'
import type { HighLevelClientConfig } from './default'
import type { DefaultOauthClient, OauthClientImpl } from '../oauth/impl'
import type { AnyOauthClient, AnyClient } from './client-type-helpers'


export interface HighLevelClientInterface<
	T extends AccessType,
	TOAuth extends DefaultOauthClient | OauthClientImpl<T>,
> {
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth
	${interfaceProperties.join('\n  ')}
}
`.trim()

	await Bun.write(CLIENT_INTERFACE_FILE, interfaceContent)
	await Bun.$`bun biome check ${CLIENT_INTERFACE_FILE} --write --unsafe`
	console.log(
		kleur.green(
			`Successfully generated HighLevelClientInterface in ${CLIENT_INTERFACE_FILE.replace(process.cwd(), '')}`,
		),
	)
}
