import path from 'node:path'
import { compileFromFile } from 'json-schema-to-typescript'
import { schemaPathsV2 } from './constants'

if (import.meta.main) {
	await generateWebhooksTypes()
}

/**
 * Generate types for each webhook schema in `schemas/v2/webhooks` directory.
 * These are JSON Schemas, not OpenAPI, so have to use the `json-schema-to-typescript` package to generate the types.
 */
async function generateWebhooksTypes() {
	const glob = new Bun.Glob(`${schemaPathsV2.webhooksJsonDir}/*.json`)

	const webhookJsonFiles = await Array.fromAsync(
		glob.scan({ absolute: true, onlyFiles: true }),
	)
	if (webhookJsonFiles.length === 0) {
		throw new Error('No webhook json files found')
	}

	await Promise.all(
		webhookJsonFiles.map(async (file) => {
			const typeName = path.basename(file, '.json')
			const webhookTypes = await compileFromFile(file, {
				$refOptions: {
					continueOnError: false,
				},
				bannerComment: `// This file is auto-generated by the generate-webhooks script
				// Do not edit this file directly.`,
				format: false, // handled by biome,
				inferStringEnumKeysFromValues: true,
				strictIndexSignatures: true,
			})
			await Bun.write(
				path.join(schemaPathsV2.webhooksTypesDir, `${typeName}.ts`),
				webhookTypes,
			)
		}),
	)

	await generateWebhookEventMap()

	await Bun.$`bun biome check ${schemaPathsV2.webhooksTypesDir} --write --unsafe`

	console.log('✨ Generated webhook types and modules')
}

/**
 * Generate a WebhookEventMap interface that maps event names to their payload types.
 * This file imports all webhook types from the types folder and creates a type-safe mapping.
 */
async function generateWebhookEventMap() {
	const glob = new Bun.Glob(`${schemaPathsV2.webhooksTypesDir}/*.ts`)

	const webhookTypeFiles = await Array.fromAsync(
		glob.scan({ absolute: true, onlyFiles: true }),
	)

	// Filter out WebhookEventMap.ts itself to avoid circular import
	const typeFiles = webhookTypeFiles.filter(
		(file) => path.basename(file) !== 'WebhookEventMap.ts',
	)

	if (typeFiles.length === 0) {
		throw new Error('No webhook type files found')
	}

	// Generate imports and type mappings
	const imports: string[] = []
	const typeMappings: string[] = []

	for (const file of typeFiles.sort()) {
		const typeName = path.basename(file, '.ts')
		const relativePath = `./${typeName}`
		imports.push(`import type { ${typeName} } from '${relativePath}'`)
		typeMappings.push(`\t${typeName}: ${typeName}`)
	}

	const webhookEventMapContent = `// This file is auto-generated by the generate-webhooks script
// Do not edit this file directly.

${imports.join('\n')}

/**
 * Map of webhook event names to their payload types.
 * This interface provides type-safe access to webhook payloads by event name.
 */
export interface WebhookEventMap {
${typeMappings.join('\n')}
}
`

	const webhookEventMapPath = path.join(
		schemaPathsV2.webhooksTypesDir,
		'WebhookEventMap.ts',
	)
	await Bun.write(webhookEventMapPath, webhookEventMapContent)
}
