import path from 'node:path'
import { compileFromFile } from 'json-schema-to-typescript'
import { schemaPathsV2 } from './constants'

if (import.meta.main) {
	await generateScopesTypes()
}

async function generateScopesTypes() {
	// there are 2 scopes json files, but we are only concerned with the main scopes.json file here
	const scopesJsonPath = path.join(schemaPathsV2.scopesJsonDir, 'scopes.json')
	const scopesJson = await Bun.file(scopesJsonPath).json()

	const generatedScopesTypes = await compileFromFile(scopesJsonPath, {
		bannerComment: `// This file is auto-generated by the generate-scopes-types script
		// Do not edit this file directly.`,
		format: false, // handled by biome,
		inferStringEnumKeysFromValues: true,
		strictIndexSignatures: true,
	})

	// Generate the Scopes const object
	const scopesConst = generateScopesConst(scopesJson)

	// Combine the types and the const
	const combinedOutput = `${generatedScopesTypes}\n\n${scopesConst}`

	await Bun.write(
		path.join(schemaPathsV2.scopesTypesDir, 'scopes.ts'),
		combinedOutput,
	)

	await Bun.$`bun run biome check ${schemaPathsV2.scopesTypesDir} --write --unsafe`

	console.log('generated scopes')
}

/**
 * Generates a const Scopes object from the scopes JSON schema.
 * Contains fully qualified scope names (e.g., 'blogs/author.readonly', 'blogs/post.write')
 * grouped by access type.
 */
function generateScopesConst(scopesJson: any): string {
	const accessTypes = ['Sub-Account', 'Agency'] as const

	const scopesEntries: string[] = []

	for (const accessType of accessTypes) {
		const accessTypeData = scopesJson.properties[accessType]
		if (!accessTypeData) continue

		const allScopes: string[] = []

		// Extract readonly scopes with .readonly suffix
		if (accessTypeData.properties.readonly?.properties) {
			for (const scopeName of Object.keys(
				accessTypeData.properties.readonly.properties,
			)) {
				allScopes.push(`'${scopeName}.readonly'`)
			}
		}

		// Extract write scopes with .write suffix
		if (accessTypeData.properties.write?.properties) {
			for (const scopeName of Object.keys(
				accessTypeData.properties.write.properties,
			)) {
				allScopes.push(`'${scopeName}.write'`)
			}
		}

		scopesEntries.push(`\t'${accessType}': [${allScopes.join(', ')}] as const`)
	}

	return `/**
* A collection of all available fully qualified scopes (as provided by the API Documentation) grouped by access type.
 * This is auto-generated from the scopes schema.
 * @example
 * ScopesCollection['Sub-Account'] // ['blogs/author.readonly', 'blogs/category.readonly', 'blogs/post.write', ...]
 * ScopesCollection['Agency'] // ['emails/schedule.readonly', 'locations.readonly', 'locations.write', ...]
 */
export const ScopesCollection = {\n${scopesEntries.join(',\n')},\n} as const`
}
