import path from 'node:path'
import kleur from 'kleur'
import { toCamelCase } from '../src/lib/utils'
import { getV2OpenApiFiles } from './generate-v2-types'

if (import.meta.main) {
	await generateClientInterface()
}

export async function generateClientInterface() {
	const CLIENT_INTERFACE_FILE = path.join(
		process.cwd(),
		'src/v2/client/interface.ts',
	)

	const schemaFiles = (await getV2OpenApiFiles())
		.filter((file) => !file.endsWith('oauth.openapi.json'))
		.map((file) => {
			const fileName = path.basename(file).replace('.openapi.json', '')
			const camelName = toCamelCase(fileName)
			const pascalName = camelName.charAt(0).toUpperCase() + camelName.slice(1)
			return { pascalName, camelName, fileName }
		})

	const importStatements = schemaFiles
		.map((file) => {
			return `import type * as ${file.pascalName} from '../types/openapi/${file.fileName}'`
		})
		.join('\n')

	/**
	 * client interfaces for each of the v2 endpoints.
	 */
	const interfaceProperties = schemaFiles.map((file) => {
		return `${file.camelName}: Client<${file.pascalName}.paths> | ClientWithAuth<${file.pascalName}.paths>`
	})

	const interfaceContent = `
// This file is generated by the ${import.meta.file} script.
// Do not edit directly.

${importStatements}

import type { Client } from 'openapi-fetch'
import type { AccessType } from '../../lib/type-utils'
import type { ClientWithAuth } from './types'
import type { HighLevelClientConfig } from './default'
import type { DefaultOauthClient, OauthClientImpl } from '../oauth/impl'

export interface HighLevelClientInterface<
	T extends AccessType,
	TOAuth extends DefaultOauthClient | OauthClientImpl<T>,
> {
	/**
	 * Exposed config object for convenience.
	 */
	_clientConfig: HighLevelClientConfig
	oauth: TOAuth
	${interfaceProperties.join('\n  ')}
}
`.trim()

	await Bun.write(CLIENT_INTERFACE_FILE, interfaceContent)
	console.log(
		kleur.green(
			`Successfully generated HighLevelClientInterface in ${CLIENT_INTERFACE_FILE.replace(process.cwd(), '')}`,
		),
	)
}
